### ISSUE TITLE
Issues raised by Poseidon Coding Team

### ISSUE THREAD

**Issue by mikenath223** [Datagirlcmr/Weather-App#1]
### Hi Selma👋

Kindly make the following adjustments:
* Consider adding node_modules to your `.gitignore` file, as it is already a pushed change you can simply delete the `node_modules` folder and make a new commit then run `npm install`, and then immediately add the `node_modules` folder to the `.gitignore` file.

**Comment by Datagirlcmr** [comment]
Thank you. I did add the node modules to my .gitignore file
